mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^', include('website.urls')),
]

website/urls.py
from django.conf.urls import url 
from . import views

app_name = 'website'

urlpatterns=[
	url(r'^$', views.index, name='index'),
]

website/models.py
from django.db import models
import datetime

class Article(models.Model):
	article_name = models.CharField(max_length=200, null=True, default='')

	article_occurences = models.IntegerField(null=True, default=1)
	def update_article_count(self):
		self.article_occurences += 1
		self.save()

	def time_under_timezone():
		return datetime.datetime.now(datetime.timezone.utc)
	creation_date = models.DateTimeField('Date of Creation', default=time_under_timezone)

	def __str__(self):
		return self.article_name

website/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
from django.template.loader import get_template, render_to_string
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist
from django.template import Context
from website.models import Article
import requests
import csv

def generate_csv_for_db_sample_data():
	try:
		with open('integration_data_sample.csv', 'w') as csvfile:
			fieldnames = ['Date Created', 'Article Name', 'Number of searches']
			writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
			writer.writeheader()
			for data in Article.objects.all():
				extracted_values = {
					'Date Created': data.creation_date,
					'Article Name': data.article_name,
					'Number of searches': data.article_occurences,
				}
				writer.writerow(extracted_values)
			return True
	except Exception as error:
		print(error)
	return False

def index(request):
	research_item = request.GET.get('search-item', '')
	if research_item:
		try:
			word_processed = Article.objects.get(article_name=research_item.lower())
			word_processed.update_article_count()
		except MultipleObjectsReturned:
			word_processed = Article.objects.filter(article_name=research_item.lower()).order_by('id').first()
			word_processed.update_article_count()
		except ObjectDoesNotExist:
			Article.objects.create(
				article_name = research_item.lower()
			)
		except Exception as error:
			print(error)

	context = {'research_item': research_item}
	return render(request, 'website/index.html', context)

website/templates/website/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Integration</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" type="image/png" href="{% static 'website/images/globe-favicon.png' %}"/>
  <link rel="stylesheet" href="{% static 'website/boots/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'website/boots/css/font-awesome.min.css' %}">
  <script src="{% static 'website/boots/js/jquery-3.2.1.min.js' %}"></script>
  <script src="{% static 'website/boots/js/bootstrap.min.js' %}"></script>
</head>

<body style="margin: 0;">

<h2 style="width: 100%; text-align: center;">Google Trends Clone<hr style="width: 200px;"></h2>

<form style="text-align: center; width: 100%;" action="{% url 'website:index' %}" method="GET">
	<div style="width: 100%; padding: 0 5% 25px 5%;">
		<input type="text" placeholder="Enter word to search..." id="search-item" name="search-item" style="font-family: serif; width: 250px; padding: 7px 4px 6px 15px; outline-color: rgba(49, 79, 79, 1); border-radius: 4px; border: 1px solid #ccc; color: #555; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);" required="required">
	</div>	
	<div>
		<button class="btn btn-danger" type="submit">Search <span class="fa fa-search"></span></button>
	</div>
</form>

<hr style="width: 200px;">

{% if research_item %}

<!-- Graph call script -->
<script type="text/javascript" src="https://ssl.gstatic.com/trends_nrtr/1480_RC02/embed_loader.js"></script> 
<!-- End Graph call script -->

<h2 style="padding-left: 10px; font-size: 28px; color: #555;">Interest Over Time <i class="fa fa-area-chart"></i></h2>
<!-- Interest over time script -->
<div id="interest-over-time-container">
<script type="text/javascript"> 
	trends.embed.renderExploreWidget(
		"TIMESERIES", 
		{"comparisonItem":[{"keyword":"{{research_item}}","geo":"ZA","time":"today 12-m"}],"category":0,"property":""}, 
		{"exploreQuery":"q={{research_item}}&geo=ZA&date=today 12-m","guestPath":"https://trends.google.com:443/trends/embed/"}
	); 
</script>
</div>
<!-- End Interest over time script -->

<br>
<br>
<br>
<hr>
<br>

<h2 style="padding-left: 10px; font-size: 28px; color: #555;">Interest By Subregion <i class="fa fa-pie-chart"></i></h2>
<!-- Sub region script -->
<div id="interest-subregion-container">
<script type="text/javascript"> 
	trends.embed.renderExploreWidget(
		"GEO_MAP", 
		{"comparisonItem":[{"keyword":"{{research_item}}","geo":"ZA","time":"today 12-m"}],"category":0,"property":""}, 
		{"exploreQuery":"q={{research_item}}&geo=ZA&date=today 12-m","guestPath":"https://trends.google.com:443/trends/embed/"}
	); 
</script>
</div>
<!-- End Sub region script -->

<br>
<br>
<hr>
<br>

{% endif %}

</body>
</html>